responses = {
    "proyector" : "Revisar la conexión entre la computadora y el proyector, asegurarse de que el proyector esté encendido y en la configuración correcta, y comprobar que la resolución de la pantalla esté configurada correctamente en la computadora.",
    "pantalla"  : "Revisar la conexión entre la computadora y el proyector, asegurarse de que el proyector esté encendido y en la configuración correcta, y comprobar que la resolución de la pantalla esté configurada correctamente en la computadora.",
    "sonido" : "Revisar las conexiones de los altavoces o auriculares, asegurarse de que el volumen esté configurado correctamente en la computadora, y comprobar que no haya programas o aplicaciones que estén utilizando el sonido al mismo tiempo.",
    "enciende" : "Revisar las conexiones de alimentación y asegurarse de que el dispositivo esté encendido",
    "internet" : "Revisar las conexiones de red, reiniciar el router o moden, y contactar al proveedor de servicios de internet para comprobar si hay problemas con la señal en la zona.",
    "wifi" : "Revisar las conexiones de red, reiniciar el router o moden, y contactar al proveedor de servicios de internet para comprobar si hay problemas con la señal en la zona.",
    "disco" : "Verificar que todas las conexiones estén bien conectadas y probar a reparar el sistema operativo. Si el problema persiste, puede ser necesario reemplazar el disco duro o llevar el dispositivo a reparación.",
    "ram" : "Verificar que la memoria RAM esté correctamente instalada y que sea compatible con el sistema, y probar a reparar el sistema operativo. Si el problema persiste, puede ser necesario reemplazar la memoria RAM o llevar el dispositivo a reparación.",
    "teclado " : "Verificar que los dispositivos estén correctamente conectados y que no estén dañados. Si el problema persiste, puede ser necesario reemplazar el teclado o el mouse o llevar el dispositivo a reparación.",
    "raton" : "Verificar que los dispositivos estén correctamente conectados y que no estén dañados. Si el problema persiste, puede ser necesario reemplazar el teclado o el mouse o llevar el dispositivo a reparación.",
    "sistema operativo"  : "Probar a reparar el sistema operativo o a reinstalarlo. Si el problema persiste, puede ser necesario llevar el dispositivo a reparación.",
    "placa base" : "Verificar que todas las conexiones estén bien conectadas y asegurar que no haya daños en la placa base. Si el problema persiste, puede ser necesario reemplazar la placa base o llevar el dispositivo a reparación.",
    "fuente" : "Verificar que la fuente de alimentación esté correctamente conectada y que no esté dañada. Si el problema persiste, puede ser necesario reemplazar la fuente de alimentación o llevar el dispositivo a reparación.",
    "tarjeta" : "Verificar que la tarjeta gráfica o de sonido esté correctamente instalada y que no esté dañada. Si el problema persiste, puede ser necesario reemplazar la tarjeta gráfica o llevar el dispositivo a reparación." ,
    "el procesador" : "Verificar que el procesador esté correctamente instalado y que no esté dañado. Si el problema persiste, puede ser necesario reemplazar el procesador o llevar el dispositivo a reparación." ,
    "batería" : "Verificar que la batería esté correctamente instalada y que no esté dañada. Si el problema persiste, puede ser necesario reemplazar la batería o llevar el dispositivo a reparación" ,
    "conexion" : "Puedes verificar que el dispositivo esté encendido y que el modo de conectividad esté habilitado. Si no verificar que el dispositivo esté conectado a la red correcta o que el router esté encendido y configurado correctamente. Si el problema persiste prueba reiniciar el dispositivo y el router o que no haya ningún obstáculo físico que esté interrumpiendo la señal. Por ultimo si el problema continua prueba a verificar que los controladores y software del dispositivo estén actualizados." ,
    "impresora" : "Verificar que el dispositivo esté conectado correctamente al ordenador o dispositivo principal. Verificar que el dispositivo esté encendido. Verificar que el controlador y software del dispositivo estén actualizados. Verificar que el dispositivo esté configurado correctamente en el sistema operativo. Reiniciar el dispositivo y el ordenador o dispositivo principal. Verificar que no haya problemas con los cables conectores." ,
    "ventilador" : "Primero verificar que los ventiladores estén funcionando correctamente y limpiar los ventiladores y las rejillas de ventilación, asegurar que el dispositivo tenga suficiente espacio para disipar el calor y revisar que los ventiladores no estén obstruidos por polvo u otros residuos. \n  Si los problemas persisten, considerar reemplazar los ventiladores o llevar el dispositivo a un técnico."
 
 }  